name: main-workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: |
          echo running workflow in main branch
          hostname
          sleep 10
          touch /tmp/grace13jun2023
      - name: second step
        run: echo "hello from second condition based step"
        if: github.event_name == 'push'
      - name: third step
        run: echo "hello from 3rd step"
